from datetime import datetime
from setup_api import setup
from mailwizz.endpoint.transactional_emails import TransactionalEmails

"""
SETUP THE API
"""
setup()

"""
CREATE THE ENDPOINT
"""
endpoint = TransactionalEmails()


"""
GET ALL ITEMS
"""
response = endpoint.get_emails(page=1, per_page=10)

"""
DISPLAY RESPONSE
"""
print(response.content)


"""
GET ONE ITEM
"""
response = endpoint.get_email(email_uid='EMAIL_UNIQUE_ID')

"""
DISPLAY RESPONSE
"""
print(response.content)


"""
CREATE A NEW EMAIL
"""
response = endpoint.create(data={
    'to_name': 'John Doe',  # required
    'to_email': 'john@doe.com',  # required
    'from_name': 'Jane Doe',  # required
    'from_email': 'jane@doe.com',  # optional
    'reply_to_name': 'Jane Doe',  # optional
    'reply_to_email': 'jane@doe.com',  # optional
    'subject': 'This is the email subject',  # required
    'body': 'Hello world!',  # required
    'plain_text': 'Hello world!',  # optional, will be autogenerated if missing
    'send_at': (datetime.now()).strftime('%Y-%m-%d %H:%M:%S'),  # required, UTC date time in same format!
})

"""
DISPLAY RESPONSE
"""
print(response.content)


"""
DELETE EMAIL
"""
response = endpoint.delete('EMAIL_UNIQUE_ID')

"""
DISPLAY RESPONSE
"""
print(response.content)
